sheori/urls.py
# path()関数のインボート
from django.urls import path
from sheori.views import spot, recommend, mypage
# ルーティングの設定
app_name = 'sheori'
urlpatterns = [
    path('spot', spot.list_view, name='spot_list'),
    path('spot/<slug:spot_id>', spot.detail_view, name='spot_detail'),
    path('spot/<slug:spot_id>/rate', spot.rate, name='spot_rate'),
    path('recommend/result/<slug:route_id>/save', recommend.route_save, name='route_save'),
    path('recommend', recommend.form_view, name='recommend_form'),
    path('recommend/result/', recommend.make_result, name='recommend_result'),
    path('recommend/result/<slug:route_id>', recommend.route_view, name='route_view'),
    path('mypage', mypage.mypage_top, name='mypage_top'),
    ]

sheori_proj/urls.py
# path()関数、include()関数のインポート
from django.urls import include, path
# 管理サイトの機能をインポート
from django.contrib import admin

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from sheori.views.register import register_view, done_view


def index(request):
    contexts = {}
    return render(request, 'index.html', contexts)


urlpatterns = [
    path('', index, name='index'),  # 追加！
    # sheori アプリケーションの URL 設定を追加
    path('sheori/', include('sheori.urls')),
    # 管理サイト
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register_view, name='register'),
    path('accounts/register/done', done_view, name='register_done'),
    # 追加ここまで
    path('sheori/', include('sheori.urls')),
]

sheori/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now
# from django.urls import reverse

GENDER_LIST = ((0, '男性'), (1, '女性'), (2, '無回答'))
dict_gender_list = dict(GENDER_LIST)
RESIDENCE_LIST = ((0, '有'), (1, '無'))
dict_residence_list = dict(RESIDENCE_LIST)
GENRE_LIST = ((0, '歴史・文化施設'), (1, '美術館・博物館'), (2, '寺社'), (3, '娯楽'), (4, '温泉・銭湯'), (5, 'グルメ'), (6, 'その他'))
genre_list = dict(GENRE_LIST)


# デフォルトであるdjango.dbのmodelsを継承して作成する
class Profile(models.Model):
    # django仕様のメタクラス(クラス自体の設定を記述)(管理画面での表示内容を設定)
    class Meta:
        verbose_name = 'ユーザー情報データ'
        verbose_name_plural = 'ユーザー情報データ'

    # ユーザーの設定。下記のフィールドとの紐づけはビューで行う
    user = models.OneToOneField(User, verbose_name='ユーザー', null=True, blank=True, on_delete=models.CASCADE)

    # フィールドの設定。コード１行がフィールド１列に対応する。
    id = models.CharField(max_length=6, primary_key=True)
    age = models.IntegerField('年齢')
    gender = models.IntegerField('性別', choices=GENDER_LIST)
    residence = models.IntegerField('金沢在住経験', choices=RESIDENCE_LIST)

    # 管理画面で表示される文字列を定義する
    def __str__(self):
        user_str = ''
        if self.user is not None:
            user_str = '(' + self.user.username + ')'

        return self.id + ' ' + str(self.age) + '歳 ' + dict_gender_list.get(self.gender)


class BusStop(models.Model):
    class Meta:
        verbose_name = 'バス停データ'
        verbose_name_plural = 'バス停データ'

    id = models.CharField('バス停ID', max_length=6, primary_key=True)
    name = models.CharField('バス停名', max_length=50)
    latitude = models.FloatField('バス停緯度')
    longitude = models.FloatField('バス停経度')

    def __str__(self):
        return 'ID: ' + self.id + ' ' + self.name


class Spot(models.Model):
    class Meta:
        verbose_name = '観光スポット情報データ'
        verbose_name_plural = '観光スポット情報データ'

    id = models.CharField('観光スポットID', max_length=6, primary_key=True)
    name = models.CharField('観光スポット名', max_length=50)
    genre = models.IntegerField('ジャンル', choices=GENRE_LIST)
    address = models.CharField('住所', max_length=100)
    latitude = models.FloatField('観光スポット緯度')
    longitude = models.FloatField('観光スポット経度')
    time_spent_ave = models.TimeField('平均滞在時間')
    detail = models.TextField('詳細情報')
    nearest_bus_stop = models.ForeignKey(BusStop, '最寄りバス停', null=True)
    dist_to_nearest_bus_stop = models.FloatField('最寄りバス停距離', null=True)

    def __str__(self):
        return 'ID: ' + self.id + ' ' + self.name


class ScoreLog(models.Model):
    class Meta:
        verbose_name = '観光スポット評価データ'
        verbose_name_plural = '観光スポット評価データ'

    profile = models.ForeignKey(Profile, verbose_name='ユーザー情報', on_delete=models.CASCADE)
    spot = models.ForeignKey(Spot, verbose_name='観光スポット', on_delete=models.CASCADE)

    score = models.IntegerField('評価')
    timestamp = models.DateTimeField('日時', auto_now_add=True)


class Route(models.Model):
    class Meta:
        verbose_name = '観光ルートデータ'
        verbose_name_plural = '観光ルートデータ'

    id = models.CharField('観光ルートID', max_length=9, primary_key=True)
    save_num = models.PositiveIntegerField('保存数', default=0)


class RouteMap(models.Model):
    class Meta:
        verbose_name = '観光ルート詳細データ'
        verbose_name_plural = '観光ルート詳細データ'

    route = models.ForeignKey(Route, on_delete=models.CASCADE)
    spot = models.ForeignKey(Spot, verbose_name='観光スポット', on_delete=models.CASCADE, null=True)
    start_point = models.ForeignKey(BusStop, verbose_name='出発地点', on_delete=models.CASCADE, null=True,
                                    related_name='start_point')
    goal_point = models.ForeignKey(BusStop, verbose_name='到着地点', on_delete=models.CASCADE, null=True,
                                   related_name='goal_point')
    order = models.IntegerField('順序')


class SaveRoute(models.Model):
    class Meta:
        verbose_name = '観光ルート保存データ'
        verbose_name_plural = '観光ルート保存データ'

    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='save_user')
    route = models.ForeignKey(Route, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)


class SpotImage(models.Model):
    """イメージモデル"""
    class Meta:
        verbose_name = '観光スポット画像データ'
        verbose_name_plural = '観光スポット画像データ'
        db_table = 'image'
    spot = models.ForeignKey(Spot, verbose_name='観光地', on_delete=models.PROTECT)
    image = models.ImageField(upload_to="image/", verbose_name='イメージ')
    created_at = models.DateTimeField(verbose_name='登録日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    def __str__(self):
        return self.work.name + ":" + str(self.data_datetime)

sheori/views.py
from django.shortcuts import render

# Create your views here.
# def index_template(request):
#     myapp_data = {
#     'app': 'Django'
#     }
#     return render(request, 'index.html', myapp_data)

sheori/views/mypage.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

import json
from sheori.models import ScoreLog, Route, SaveRoute


@login_required
def mypage_top(request):
    user = request.user
    profile = user.profile
    mylogs = ScoreLog.objects.filter(profile_id=profile.id)
    myroutes = SaveRoute.objects.filter(user_id=profile.id)
    myroute_list = []
    for myroute in myroutes:
        myroute_saved = Route.objects.filter(id=myroute.route.id)
        myroute_list.append(myroute_saved[0])

    mypage_data = {
        'profile': profile,
        'logs': mylogs,
        'saved_routes': myroute_list,
    }

    return render(request, 'sheori/mypage.html', mypage_data)

sheori/views/recommend.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import re
import datetime
import pandas as pd
from math import sin, cos, acos, radians





from sheori.scripts.recommend.recommend_main import RecommendRoute
from sheori.scripts.recommend.cross_tabulation import CrossTable

from sheori.models import Spot, BusStop, RouteMap, Route, SaveRoute

EARTH_RAD = 6378.137
METER_PER_MINUTE = 2.778 * 60


def form_view(request):  # フォームを表示
    return render(request, 'sheori/recommend_form.html')


def make_result(request):  # フォームの入力をAPIに伝達、リターン値を用いてテンプレートに表示
    var = request.GET
    start_point = var.get('start_point')
    goal_point = (var.get('goal_point'))
    must_spot = var.get('must_spot')
    start_time = (var.get('start_time'))
    goal_time = (var.get('goal_time'))
    # results = RecommendRoute(gender, household, station, limit).main()
    route_id = RecommendRoute(start_point, goal_point, must_spot, start_time, goal_time, request).main()
    # result = [[route_spots_copy], sum_time, [time_list], [dist_list]]
    print("AAAAAAAAAAAAAAAAAAAAAA")
    return redirect('sheori:route_view', route_id)


def route_view(request, route_id):
    route = Route.objects.get(id=route_id)
    maps = RouteMap.objects.filter(route=route)
    maps = sorted(maps, key=lambda map_: map_.order)
    route_spots = []
    time_list = []
    dist_list = []
    sum_time = datetime.time(0, 00, 00)
    for i in range(len(maps)):
        if i == 0:
            route_spots.append(maps[i].start_point.id)
        elif maps[i] == maps[-1]:
            route_spots.append(maps[i].goal_point.id)
        else:
            route_spots.append(maps[i].spot.id)

    for i in range(len(route_spots) - 1):
        if i != 0:
            df_spot, df_user, df_bus_stop = read_data()
            df_spot_extracted = df_spot[df_spot['id'] == route_spots[int(i)]]
            # spot_spend_time_list = df_spot_extracted['time_spent_ave'].values[0].split(':')
            spot_spend_time = df_spot_extracted['time_spent_ave'].values[0]
            # spot_spend_time = datetime.time(int(spot_spend_time_list[0]), int(spot_spend_time_list[1]),
            #                                 int(spot_spend_time_list[2]))
            sum_time = add_times(sum_time, spot_spend_time).time()
            time_list.append(spot_spend_time)
        spot_a = get_position(route_spots[i])
        spot_b = get_position(route_spots[i + 1])
        dist_a_b = dist_on_sphere(spot_a, spot_b)
        time_a_b = get_time(dist_a_b)
        time_a_b = minute_to_hour(time_a_b)
        dist_a_b = round(dist_a_b * 1000)
        # if type(sum_time) == datetime.datetime:
        #     sum_time = sum_time.time()
        sum_time = add_times(sum_time, time_a_b).time()
        time_list.append(time_a_b)
        dist_list.append(dist_a_b)
    results = [route_spots, sum_time, time_list, dist_list]
    spot_name = []
    spot_id = []
    for x in results[0]:
        if re.match('B', x):
            spot_name.append(BusStop.objects.get(id=x).name)
        else:
            spot_name.append(Spot.objects.get(id=x).name)
    results[0] = spot_name
    spot_names = results[0]
    sum_time = results[1]
    time_list = results[2]
    dist_list = results[3]
    start_list = [spot_names.pop(0), time_list.pop(0), dist_list.pop(0)]
    main = []
    for i in range(len(spot_names) - 1):
        main_list = []
        main_list.append(Spot.objects.get(name=spot_names[i]))
        main_list.append(time_list[i * 2])
        main_list.append(time_list[i * 2 - 1])
        main_list.append(dist_list[i])
        main.append(main_list)
    goal_list = spot_names[-1]
    route_ = Route.objects.get(id=route_id)
    save_condition = SaveRoute.objects.filter(user=request.user.profile).filter(route=route_)
    if len(save_condition) == 0:
        save = True
    else:
        save = False
    save_num = SaveRoute.objects.filter(route=route_).count()
    packed_route = {
        'route': route_id,
        'start_list': start_list,
        'main': main,
        'goal_list': goal_list,
        'sum_time': sum_time,
        'save': save,
        'save_num': save_num,
    }
    return render(request, 'sheori/recommend_result.html', packed_route)


@login_required
def route_save(request, route_id):
    route_ = Route.objects.get(id=route_id)
    route_save_condition = SaveRoute.objects.filter(user=request.user.profile).filter(route=route_)
    if len(route_save_condition) != 0:
        save_data = SaveRoute.objects.get(user=request.user.profile, route=route_)
        save_data.delete()
        route_.save_num -= 1
        route_.save()
    else:
        SaveRoute.objects.create(
            user=request.user.profile,
            route=route_,
        )
        route_.save_num += 1
        route_.save()
    return redirect('sheori:route_view', route_id)


def get_position(any_id):
    df_spot, df_user, df_bus_stop = read_data()
    if re.match('B', any_id):
        df_spot_extracted = df_bus_stop[df_bus_stop["id"] == str(any_id)]
        spot = df_spot_extracted['latitude'].values[0], df_spot_extracted['longitude'].values[0]
    else:
        df_spot_extracted = df_spot[df_spot["id"] == str(any_id)]
        spot = df_spot_extracted['latitude'].values[0], df_spot_extracted['longitude'].values[0]
    return spot


def read_data():
    df_spot = pd.DataFrame.from_records(list(Spot.objects.values()))
    df_bus_stop = pd.DataFrame.from_records(list(BusStop.objects.values()))
    df_user, _ = CrossTable().get()
    return df_spot, df_user, df_bus_stop


def get_time( dist):
    time = dist * 1000 / METER_PER_MINUTE
    return time


def add_times(time, add_time):
    if type(time) == datetime.datetime:
        time = time.time()
    if type(add_time) == datetime.datetime:
        add_time = add_time.time()
    added_time = datetime.datetime.combine(datetime.date.today(), time) +\
                 datetime.timedelta(hours=add_time.hour, minutes=add_time.minute)
    return added_time


def latlng_to_xyz(lat, lng):
    rlat, rlng = radians(lat), radians(lng)
    coslat = cos(rlat)
    return coslat * cos(rlng), coslat * sin(rlng), sin(rlat)


def dist_on_sphere(pos0, pos1, radius=EARTH_RAD):
    xyz0, xyz1 = latlng_to_xyz(*pos0), latlng_to_xyz(*pos1)
    return acos(sum(x * y for x, y in zip(xyz0, xyz1))) * radius


def minute_to_hour(minute):
    minute = round(minute)
    hour = minute // 60
    minute = minute % 60
    time = datetime.time(hour, minute, 00)
    return time

sheori/views/register.py
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from sheori.register_form import RegisterForm

class RegisterView(CreateView):
    template_name = 'registration/register_form.html'
    form_class = RegisterForm
    success_url = reverse_lazy('register_done')

register_view = RegisterView.as_view()

class DoneView(TemplateView):
    template_name = 'registration/register_done.html'

done_view = DoneView.as_view()

sheori/views/spot.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.core.paginator import Paginator
from sheori.models import Spot, ScoreLog

import random

message_rate_created = '評価が登録されました！'
message_rate_updated = '評価が更新されました！'


def list_view(request):
    spot_list = Spot.objects.all().order_by('id')

    paginator = Paginator(spot_list, 10)

    try:
        page = int(request.GET.get('page'))
    except:
        page = 1

    spots = paginator.get_page(page)
    return render(request, 'sheori/spot_list.html', {'spots': spots, 'page': page, 'last_page': paginator.num_pages})


def detail_view(request, spot_id):
    spot = get_object_or_404(Spot, id=spot_id)

    try:
        page = int(request.GET.get('from_page'))
    except:
        page = 1

    try:
        log = ScoreLog.objects.get(profile_id=request.user.profile.id, spot_id=spot_id)
        current_score = log.score
    except:
        current_score = -1

    return render(request, 'sheori/spot_detail.html',
                  {'spot': spot, 'page': page, 'current_score': current_score})


# 追加！
@login_required
def rate(request, spot_id):
    spot = get_object_or_404(Spot, id=spot_id)

    log, created = ScoreLog.objects.update_or_create(
        defaults={'score': request.POST.get('score')},
        profile_id=request.user.profile.id,
        spot_id=spot_id,
    )

    if created:
        messages.success(request, message_rate_created)
    else:
        messages.success(request, message_rate_updated)

    return redirect('sheori:spot_detail', spot_id=spot_id)

sheori/templates/sheori/mypage.html
{% extends "base.html" %}
{% load mathfilters %}

{% block title %}マイページ{% endblock title %}

{% block content %}
<div class="head p-5">
  <div class="spot-list p-3 font-deep">
    <h4 class="mt-4 border-b">マイページ</h4>

    <h5>基本情報</h5>
    <p><b>{{ user.username }}</b> さん</p>
    <p>年齢: {{ user.profile.age }}歳</p>
    <p>性別: {{ user.profile.get_gender_display }}</p>
    <p></p>
    <p>ユーザー名またはパスワードの編集は <a href="/accounts">こちら</a>(未実装)</p>

    <hr>
    <h5 class="mt-4 border-b">観光スポット評価履歴</h5>

    <table class="table table-striped table-bordered">
    <thead>
        <tr>
        <th scope="col">観光スポット名称</th>
        <th scope="col">評価</th>
        </tr>
    </thead>
    <tbody>
        {% for log in logs %}
        <tr>
        <td>
            <a href="{% url 'sheori:spot_detail' spot_id=log.spot.id %}">
                {{ log.spot.name }}
            </a>
        </td>
        <td>{{ log.score }}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>

    <hr>
    <h5 class="mt-4 border-b">保存ルート</h5>

    <table class="table table-striped table-bordered">
    <thead>
        <tr>
        <th scope="col">ルートID</th>
        </tr>
    </thead>
    <tbody>
        {% for route in saved_routes %}
        <tr>
        <th scope="row">
          <a href="{% url 'sheori:route_view' route_id=route.id %}">
              {{ route.id }}
          </a>
        </th>
        </tr>
        {% endfor %}
    </tbody>
    </table>
  </div>
</div>
{% endblock %}

sheori/templates/sheori/recommend_result.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load staticfiles %}

{% block title %}おすすめルートの検索結果{% endblock title %}

{% block content %}
<div class="head p-5">
  <div class="recommend-result p-3 font-deep">
    <div class="row mx-3 mt-3 border-b">
      <div class="col-8">
        <h4>おすすめコース</h4>
      </div>
      <div class="col-2 text-right">
        {% if save %}
        <h4><a href="{% url 'sheori:route_save' route_id=route %}" class="btn btn-light btn-sm">保存</a></h4>
        {% else %}
        <h4><a href="{% url 'sheori:route_save' route_id=route %}" class="btn btn-primary btn-sm">保存済</a></h4>
        {% endif %}
      </div>
      <div class="col-2 text-left">
        <p>保存数: {{ save_num }}</p>
      </div>
    </div>
    <div class="recommend-route">
      <div class="row ml-3 mr-3">
        <div class="col-6">
          <div class="route-inner">
            <p>合計所要時間: {{ sum_time }}</p>
            <div class="row pt-1">
              <div class="col-2 text-center">
                <div class="circle">
                </div>
              </div>
              <div class="col-10 pl-1">
                <div class="text-left pl-3 spot-title">
                  <h5 class="mb-1">出発場所: {{ start_list.0 }}</h5>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-2 text-center">
                <div class="line">
                </div>
              </div>
              <div class="col-10 pl-1">
                <div class="text-left pl-3 route-time">
                  <p>移動時間目安: {{ start_list.1 }} ({{ start_list.2 }}m)</p>
                </div>
              </div>
            </div>
            {% for main_ in main %}
            <div class="row pt-1">
              <div class="col-2 text-center">
                <div class="circle">
                </div>
              </div>
              <div class="col-10 pl-1">
                <div class="text-left pl-3 spot-title">
                  <h5 class="mb-1">{{ main_.0.name }}: <a class="route-spot-detail" href="{% url 'sheori:spot_detail' spot_id=main_.0.id %}">詳細</a> (滞在時間: {{ main_.1 }})</h5>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-2 text-center">
                <div class="line">
                </div>
              </div>
              <div class="col-10 pl-1">
                <div class="text-left pl-3 route-time">
                  <p>移動時間目安: {{ main_.2 }} ({{ main_.3 }}m)</p>
                </div>
              </div>
            </div>
            {% endfor %}
            <div class="row pt-1">
              <div class="col-2 text-center">
                <div class="circle">
                </div>
              </div>
              <div class="col-10 pl-1">
                <div class="text-left pl-3 spot-title">
                  <h5 class="mb-1">到着場所: {{ goal_list }}</h5>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-6 map">
          <h5 class="mb-5">MAP(sample)</h5>
          <img src="{% static 'sheori/img/map.png' %}">
        </div>
      </div>
    </div>
    <div class="row my-3">
      <div class="col-6">
      </div>
      <div class="col-5 text-right">
        <a href="{% url 'sheori:recommend_form' %}" class="btn btn-secondary btn-sm">再検索</a>
      </div>
      <div class="col-1">
      </div>
    </div>
  </div>
  <div class="row my-3">
    <div class="col-1">
    </div>
    <div class="col-5 text-left">
      <a href="{% url 'index' %}" class="btn btn-secondary btn-sm">戻る</a>
    </div>
    <div class="col-6">
    </div>
  </div>
</div>
{% endblock content %}

sheori/templates/sheori/spot_detail.html
{% extends "base.html" %}
{% load mathfilters %}
{% load staticfiles %}

{% block title %}物件の一覧{% endblock title %}

{% block content %}
<div class="head p-5">
  <div class="spot-list p-3 font-deep">
    <h4 class="mt-4 border-b">物件の詳細</h4>

    <table class="table table-striped table-bordered font-deep list-table">
        <tbody>
            <tr>
                <th scope="row">名称</th>
                <td>{{ spot.name }}</td>
            </tr>
            <tr>
                <th scope="row">住所</th>
                <td>{{ spot.address }}</td>
            </tr>
            <tr>
                <th scope="row">説明</th>
                <td>{{ spot.detail }}</td>
            </tr>
        </tbody>
    </table>

    <p>この物件を評価してください。</p>
    <form action="{% url 'sheori:spot_rate' spot_id=spot.id %}" method="POST">
        {% csrf_token %}
        {% if 0 <= current_score %}
        <input type="number" name="score" min="1" max="5" value="{{ current_score }}" required />
        {% else %}
        <input type="number" name="score" min="1" max="5" required />
        {% endif %}
        <input type="submit" name="submit" value="送信" />
    </form>

  </div>
  <div class="row my-3">
    <div class="col-6 ml-3 text-left">
      <a href="{% url 'sheori:spot_list' %}?page={{ page }}" class="btn btn-secondary btn-sm">一覧へ戻る</a>
    </div>
    <div class="col-6">
    </div>
  </div>
</div>
{% endblock %}





{% block extra_js %}
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
    integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
    crossorigin=""></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-tilelayer-geojson/1.0.4/TileLayer.GeoJSON.min.js"></script>
<script src="{% static 'iekari/js/map_preview.js' %}"></script>
{% endblock %}

sheori/templates/sheori/spot_list.html
{% extends "base.html" %}
{% load mathfilters %}

{% block title %}観光スポットの一覧{% endblock title %}

{% block content %}

    <div class="head p-5">
        <div class="spot-list p-3 font-deep">
            <h4 class="my-3 border-b">観光スポット一覧</h4>
            <table class="table table-striped table-bordered font-deep">
                <thead>
                    <tr>
                        <th scope="col">観光スポットID</th>
                        <th scope="col">名称</th>
                        <th scope="col">住所</th>
                        <th scope="col">平均滞在時間</th>
                        <th scope="col">最寄りバス停</th>
                    </tr>
                </thead>
                <tbody>
                    {% for spot in spots %}
                    <tr>
                        <th scope="row"><!---変更--->
                            <a href="{% url 'sheori:spot_detail' spot_id=spot.id %}">
                                {{ spot.id }}
                            </a>
                        </th>
                        <td>{{ spot.name }}</td>
                        <td>{{ spot.address }}</td>
                        <td>{{ spot.time_spent_ave }}</td>
                        <td>{{ spot.nearest_bus_stop.name }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="row my-3">
          <div class="col-1">
          </div>
          <div class="col-5 text-left">
{% if 1 < page %}
              <a class="a-light" href="{% url 'sheori:spot_list' %}?page={{ page|sub:1 }}">前のページ</a>
{% endif %}
          </div>
          <div class="col-5 text-right">
{% if page < last_page %}
              <a class="a-light" href="{% url 'sheori:spot_list' %}?page={{ page|add:1 }}">次のページ</a>
{% endif %}
          </div>
          <div class="col-1">
          </div>
        </div>
    </div>
{% endblock %}